[package]
name = "assertables"
version = "4.0.0"
authors = ["Joel Parker Henderson <joel@joelparkerhenderson.com>"]
edition = "2021"
description = "Assertables: Rust crate of macros `assert…!`, `assume…!`, `assure…!`, all for runtime reliability checking. By SixArm.com."
readme = "README.md"
repository = "https://github.com/joelparkerhenderson/assertable-rust-crate/"
license = "MIT OR Apache-2.0 OR GPL-2.0-only"
keywords = ["assert", "assume", "assure", "macro", "test"]
categories = ["development-tools", "development-tools::testing", "rust-patterns"]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[dependencies]

